
import React, { useState, useMemo } from 'react';
import { 
  Scale, 
  Briefcase, 
  FileCheck, 
  ShieldAlert, 
  Search, 
  Eye, 
  BookOpen, 
  Library, 
  Gavel, 
  ExternalLink, 
  ChevronRight,
  Info,
  Download,
  Zap,
  FileText,
  Filter,
  Sparkles,
  ArrowRight,
  ShieldCheck,
  Fingerprint,
  History,
  Lock,
  CheckCircle,
  FileWarning,
  FileDown
} from 'lucide-react';
import { VerificationResult, UserProfile, ApplicableLaw, RiskLevel } from '../types';
import Verify from './Verify';

// Enhanced Cyber Law Database (India-Centric)
const CYBER_LAW_DATABASE: ApplicableLaw[] = [
  {
    title: "Information Technology Act, 2000",
    section: "Section 66",
    description: "Computer related offences. Covers any person who, with intent to cause damage, commits any act that destroys, alters or diminishes the value of any information.",
    relevanceLevel: "Direct",
    category: "Evidence"
  },
  {
    title: "Information Technology Act, 2000",
    section: "Section 66C",
    description: "Punishment for identity theft. Directly applicable to deepfake impersonations and credential harvesting.",
    relevanceLevel: "Direct",
    category: "Identity"
  },
  {
    title: "Information Technology Act, 2000",
    section: "Section 66D",
    description: "Cheating by personation by using computer resource. Primary section for pursuing deepfake-based financial fraud.",
    relevanceLevel: "Direct",
    category: "Fraud"
  },
  {
    title: "Information Technology Act, 2000",
    section: "Section 66E",
    description: "Punishment for violation of privacy. Capturing or transmitting images of private parts without consent (Deepfake morphing).",
    relevanceLevel: "Direct",
    category: "Privacy"
  },
  {
    title: "Information Technology Act, 2000",
    section: "Section 67A",
    description: "Punishment for publishing/transmitting sexually explicit material in electronic form. Highly relevant for Non-Consensual Deepfake Imagery (NCDI).",
    relevanceLevel: "Direct",
    category: "Privacy"
  },
  {
    title: "Bhartiya Nyaya Sanhita (BNS)",
    section: "Section 319 / 318",
    description: "Cheating and Personation. Replaces/augments IPC 419/420 for digital fraudulent inducement.",
    relevanceLevel: "Supporting",
    category: "Fraud"
  },
  {
    title: "Bhartiya Nyaya Sanhita (BNS)",
    section: "Section 356",
    description: "Defamation. Applicable when deepfakes are used to tarnish the reputation of a public figure or private citizen.",
    relevanceLevel: "Direct",
    category: "Defamation"
  },
  {
    title: "Copyright Act, 1957",
    section: "Section 51",
    description: "Infringement of copyright. Relevant for AI models trained on copyrighted data without authorization.",
    relevanceLevel: "Contextual",
    category: "Copyright"
  }
];

const TruthLens: React.FC<{ userProfile: UserProfile | null; onComplete: (r: VerificationResult) => void; isLoggedIn: boolean; lastResult?: VerificationResult | null }> = ({ userProfile, onComplete, isLoggedIn, lastResult }) => {
  const [isVerificationMode, setIsVerificationMode] = useState(false);
  const [lawSearchQuery, setLawSearchQuery] = useState('');
  const [filterLevel, setFilterLevel] = useState<string>('All');
  const [selectedCategory, setSelectedCategory] = useState<string>('All');

  const crimeCategories = ['All', 'Fraud', 'Privacy', 'Defamation', 'Identity', 'Copyright', 'Evidence'];

  const handleDownloadReport = () => {
    if (!lastResult) return;
    const reportContent = `
VERITRUST AI FORENSIC EVIDENCE PACKET
---------------------------------------
CASE ID: ${lastResult.id}
TIMESTAMP: ${new Date(lastResult.timestamp).toLocaleString('en-IN')}
JURISDICTION: India (IT Act / BNS)
CONTENT: ${lastResult.content}
FINGERPRINT: ${lastResult.fingerprint}
INTEGRITY HASH: ${lastResult.verificationHash}

FORENSIC VERDICT:
- Probability of Manipulation: ${lastResult.fakeProbability}%
- Risk Level: ${lastResult.riskLevel.toUpperCase()}
- AI Confidence: ${Math.round(lastResult.confidenceScore * 100)}%
- Origin: ${lastResult.originLabel}

INVESTIGATIVE REASONING:
${lastResult.reasoning}

APPLICABLE STATUTES (INDIAN LAW):
${lastResult.legalAssessment?.applicableLaws?.map(l => `- ${l.section}: ${l.title} (${l.relevanceLevel})`).join('\n') || 'None identified by automated scan.'}

COURT SUMMARY:
${lastResult.legalAssessment?.courtReadySummary || 'N/A'}

EXPERT RECOMMENDATION:
${lastResult.legalAssessment?.expertRecommendation || 'N/A'}

---------------------------------------
CONFIDENTIAL: Generated by VeriTrust AI Forensic Engine (Gov-Grade)
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Forensic_Evidence_Report_${lastResult.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const recommendedLaws = useMemo(() => {
    if (!lastResult) return [];
    return CYBER_LAW_DATABASE.filter(law => {
      if (lastResult.fraudRisk?.isScam && law.category === 'Fraud') return true;
      if (lastResult.originLabel === 'AI-Generated' && (law.category === 'Identity' || law.category === 'Copyright')) return true;
      if (lastResult.riskLevel === RiskLevel.HIGH && law.relevanceLevel === 'Direct') return true;
      return false;
    }).slice(0, 3);
  }, [lastResult]);

  const filteredLaws = useMemo(() => {
    return CYBER_LAW_DATABASE.filter(law => {
      const matchesSearch = 
        law.title.toLowerCase().includes(lawSearchQuery.toLowerCase()) ||
        law.section.toLowerCase().includes(lawSearchQuery.toLowerCase()) ||
        law.description.toLowerCase().includes(lawSearchQuery.toLowerCase());
      const matchesLevel = filterLevel === 'All' || law.relevanceLevel === filterLevel;
      const matchesCategory = selectedCategory === 'All' || law.category === selectedCategory;
      return matchesSearch && matchesLevel && matchesCategory;
    });
  }, [lawSearchQuery, filterLevel, selectedCategory]);

  if (isVerificationMode) {
    return (
      <div className="space-y-6">
        <button 
          onClick={() => setIsVerificationMode(false)}
          className="text-slate-500 font-bold text-sm flex items-center gap-2 hover:text-slate-800 transition-all px-4 py-2 bg-slate-100 rounded-xl w-fit"
        >
          <Search size={16}/> Back to Command Center
        </button>
        <Verify 
          onComplete={onComplete} 
          isLoggedIn={isLoggedIn} 
          onAuthNeeded={() => {}} 
          userProfile={userProfile}
          title="Evidence Uplink"
        />
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto space-y-10 animate-in fade-in duration-700 pb-20">
      {/* Hero Header */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-8 bg-slate-900 p-12 rounded-[50px] shadow-3xl relative overflow-hidden">
        <div className="relative z-10 space-y-4">
          <div className="flex items-center gap-4">
            <div className="bg-blue-600 p-3 rounded-2xl shadow-xl shadow-blue-500/20">
              <Scale size={32} className="text-white" />
            </div>
            <div>
              <h2 className="text-4xl font-black text-white tracking-tight">TruthLens <span className="text-blue-500">Forensics</span></h2>
              <p className="text-slate-400 font-medium">Cyber-Legal Intelligence & Evidence Integrity Suite</p>
            </div>
          </div>
          <div className="flex flex-wrap gap-4 pt-4">
            <div className="px-5 py-2.5 bg-white/5 border border-white/10 rounded-2xl flex items-center gap-3">
              <ShieldCheck size={18} className="text-blue-400" />
              <span className="text-xs font-bold text-white uppercase tracking-widest">Bar-Certified Protocol</span>
            </div>
            <div className="px-5 py-2.5 bg-white/5 border border-white/10 rounded-2xl flex items-center gap-3">
              <Fingerprint size={18} className="text-indigo-400" />
              <span className="text-xs font-bold text-white uppercase tracking-widest">AES-256 Ledgering</span>
            </div>
          </div>
        </div>
        
        <div className="relative z-10">
          <button 
            onClick={() => setIsVerificationMode(true)}
            className="group px-12 py-7 bg-white text-slate-900 rounded-[30px] font-black text-xl flex items-center gap-4 shadow-2xl hover:bg-blue-50 transition-all hover:scale-[1.02] active:scale-95"
          >
            <FileCheck size={28} className="text-blue-600" />
            Ingest Evidence
            <ArrowRight size={24} className="group-hover:translate-x-1 transition-transform" />
          </button>
        </div>
        
        {/* Abstract Background Element */}
        <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-blue-600/10 rounded-full blur-[120px] -mr-64 -mt-64"></div>
      </div>

      {/* Forensic Intelligence Summary Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {[
          { icon: <Briefcase className="text-blue-600"/>, label: "Active Files", value: "12", sub: "3 Critical" },
          { icon: <History className="text-indigo-600"/>, label: "Analysis Hours", value: "148", sub: "This Month" },
          { icon: <Gavel className="text-slate-900"/>, label: "Integrity Ratio", value: "99.4%", sub: "Courtroom Safe" },
          { icon: <ShieldAlert className="text-red-600"/>, label: "Manipulation Hits", value: "8", sub: "Deepfakes Found" }
        ].map((stat, i) => (
          <div key={i} className="bg-white p-8 rounded-[40px] border border-slate-100 shadow-sm hover:shadow-xl transition-all">
            <div className="bg-slate-50 w-14 h-14 rounded-2xl flex items-center justify-center mb-6">{stat.icon}</div>
            <p className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em] mb-1">{stat.label}</p>
            <p className="text-3xl font-black text-slate-900">{stat.value}</p>
            <p className="text-xs font-bold text-slate-500 mt-1">{stat.sub}</p>
          </div>
        ))}
      </div>

      {/* Case Context & AI Legal Analyst - REACTS TO LAST SCAN */}
      {lastResult ? (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          <div className="lg:col-span-8 bg-white p-12 rounded-[50px] border border-slate-100 shadow-2xl space-y-10 relative overflow-hidden">
             <div className="flex items-center justify-between border-b border-slate-50 pb-8">
               <div className="space-y-1">
                 <h3 className="text-2xl font-black text-slate-900 flex items-center gap-3">
                   <Sparkles className="text-blue-600" size={28} /> AI Forensic Analyst
                 </h3>
                 <p className="text-slate-500 text-sm">Automated evaluation for Case ID: <span className="font-mono font-bold">#{lastResult.id}</span></p>
               </div>
               <div className={`px-6 py-2 rounded-2xl text-xs font-black uppercase tracking-widest ${lastResult.riskLevel === RiskLevel.HIGH ? 'bg-red-50 text-red-600 border border-red-100' : 'bg-emerald-50 text-emerald-600 border border-emerald-100'}`}>
                 Admissibility Risk: {lastResult.riskLevel}
               </div>
             </div>

             <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
               <div className="space-y-6">
                 <div>
                   <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-3">Forensic Verdict</p>
                   <p className="text-lg text-slate-700 font-bold leading-relaxed">"{lastResult.reasoning}"</p>
                 </div>
                 <div className="p-6 bg-slate-50 rounded-3xl border border-slate-100">
                    <div className="flex items-center gap-3 mb-3">
                      <Lock size={18} className="text-indigo-600" />
                      <p className="text-xs font-black text-slate-800 uppercase tracking-wider">Integrity Ledger</p>
                    </div>
                    <p className="text-[10px] font-mono text-slate-500 break-all">{lastResult.verificationHash}</p>
                 </div>
               </div>

               <div className="space-y-8">
                  <div>
                    <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-4">Statutory Links</p>
                    <div className="space-y-3">
                      {recommendedLaws.map((law, i) => (
                        <div key={i} className="flex items-center gap-4 group cursor-pointer">
                          <div className="p-2 bg-blue-50 rounded-lg text-blue-600 group-hover:bg-blue-600 group-hover:text-white transition-all">
                            <BookOpen size={16}/>
                          </div>
                          <div>
                            <p className="text-xs font-black text-slate-800">{law.section}</p>
                            <p className="text-[10px] text-slate-400">{law.title}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                  
                  <button 
                    onClick={handleDownloadReport}
                    className="w-full py-4 bg-slate-900 text-white rounded-2xl font-black text-xs uppercase tracking-widest flex items-center justify-center gap-3 hover:bg-blue-700 transition-all shadow-xl active:scale-95"
                  >
                    <FileDown size={18} /> Export Forensic Evidence Packet
                  </button>
               </div>
             </div>
          </div>

          <div className="lg:col-span-4 bg-indigo-900 p-12 rounded-[50px] text-white flex flex-col justify-between shadow-2xl relative overflow-hidden">
             <div className="relative z-10 space-y-8">
               <div className="space-y-2">
                 <h4 className="text-xl font-black">Chain of Custody</h4>
                 <p className="text-indigo-200 text-xs">Immutable processing timeline</p>
               </div>

               <div className="space-y-8">
                 {[
                   { icon: <ArrowRight />, label: "Initial Upload", time: "T-0:00", active: true },
                   { icon: <Search />, label: "Spectral Scan", time: "T-0:02", active: true },
                   { icon: <Lock />, label: "Hash Locked", time: "T-0:05", active: true },
                   { icon: <Scale />, label: "Legal Trace", time: "T-0:08", active: true }
                 ].map((step, i) => (
                   <div key={i} className="flex items-center gap-6 relative">
                     {i < 3 && <div className="absolute left-6 top-10 w-0.5 h-10 bg-indigo-700"></div>}
                     <div className={`w-12 h-12 rounded-2xl flex items-center justify-center transition-all ${step.active ? 'bg-blue-500 text-white shadow-lg' : 'bg-indigo-800 text-indigo-400'}`}>
                       {step.icon}
                     </div>
                     <div>
                       <p className="text-sm font-black uppercase tracking-widest">{step.label}</p>
                       <p className="text-[10px] text-indigo-400 font-bold">{step.time}</p>
                     </div>
                   </div>
                 ))}
               </div>
             </div>
             <div className="absolute top-0 right-0 w-64 h-64 bg-white/5 rounded-full blur-3xl -mr-32 -mt-32"></div>
          </div>
        </div>
      ) : (
        <div className="bg-slate-50 border-2 border-dashed border-slate-200 p-20 rounded-[50px] text-center space-y-6">
          <div className="w-20 h-20 bg-white rounded-full shadow-lg flex items-center justify-center mx-auto text-slate-300">
             <Eye size={40} />
          </div>
          <div className="max-w-md mx-auto space-y-2">
            <h3 className="text-2xl font-black text-slate-900">No Active Case</h3>
            <p className="text-slate-500 font-medium">Upload evidence to populate the Forensic Intelligence dashboard and legal analytical engine.</p>
          </div>
        </div>
      )}

      {/* Supreme Intelligence Law Search Tool */}
      <div className="bg-slate-950 rounded-[60px] p-16 shadow-3xl space-y-12 border border-slate-900 relative">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-8">
          <div className="space-y-2">
            <div className="flex items-center gap-4">
              <Library size={32} className="text-blue-500" />
              <h3 className="text-3xl font-black text-white tracking-tight">Digital Statute Intelligence</h3>
            </div>
            <p className="text-slate-400 text-sm max-w-xl">Deep integration with the IT Act, BNS, and Indian Evidence Act protocols for rapid discovery.</p>
          </div>
          <div className="flex flex-wrap items-center gap-2 p-1 bg-white/5 rounded-[22px] border border-white/10">
            {['All', 'Direct', 'Supporting'].map((level) => (
              <button
                key={level}
                onClick={() => setFilterLevel(level)}
                className={`px-6 py-2.5 rounded-[18px] text-[10px] font-black uppercase tracking-widest transition-all ${
                  filterLevel === level ? 'bg-blue-600 text-white shadow-xl' : 'text-slate-500 hover:text-white'
                }`}
              >
                {level}
              </button>
            ))}
          </div>
        </div>

        {/* Category Search Matrix */}
        <div className="space-y-8">
          <div className="flex flex-wrap gap-3">
             {crimeCategories.map(cat => (
               <button
                 key={cat}
                 onClick={() => setSelectedCategory(cat)}
                 className={`px-7 py-3.5 rounded-2xl text-[10px] font-black uppercase tracking-[0.1em] border transition-all ${
                   selectedCategory === cat 
                   ? 'bg-white text-slate-900 border-white shadow-[0_0_30px_rgba(255,255,255,0.15)] scale-105' 
                   : 'bg-transparent text-slate-500 border-slate-800 hover:border-slate-600'
                 }`}
               >
                 {cat}
               </button>
             ))}
          </div>

          <div className="relative group">
            <Search className="absolute left-8 top-1/2 -translate-y-1/2 text-slate-600 group-focus-within:text-blue-500 transition-colors" size={28} />
            <input 
              type="text" 
              placeholder="Query Indian statutes by keyword, section, or case type (e.g. 'Identity Theft v. Deepfake')..."
              value={lawSearchQuery}
              onChange={(e) => setLawSearchQuery(e.target.value)}
              className="w-full pl-20 pr-10 py-8 bg-white/5 border border-white/10 rounded-[30px] text-white outline-none focus:ring-4 focus:ring-blue-500/20 focus:border-blue-500/50 transition-all font-bold text-xl placeholder:text-slate-700"
            />
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {filteredLaws.length > 0 ? (
            filteredLaws.map((law, idx) => (
              <div key={idx} className="bg-white/5 border border-slate-900 p-10 rounded-[40px] hover:bg-white/10 transition-all group flex flex-col justify-between relative h-full">
                <div className="space-y-6">
                  <div className="flex items-start justify-between">
                    <div className="w-16 h-16 bg-blue-500/10 rounded-2xl flex items-center justify-center text-blue-400 group-hover:scale-110 transition-transform">
                      <Gavel size={28} />
                    </div>
                    <div className="flex flex-col items-end gap-2">
                      <span className="text-[10px] font-black uppercase tracking-[0.15em] text-slate-500">{law.category}</span>
                      <span className={`text-[9px] font-black uppercase tracking-tight px-3 py-1 rounded-full border ${
                        law.relevanceLevel === 'Direct' ? 'border-blue-500 text-blue-400' : 'border-slate-700 text-slate-600'
                      }`}>
                        {law.relevanceLevel}
                      </span>
                    </div>
                  </div>
                  <div>
                    <h4 className="text-white font-black text-xl mb-2 leading-tight group-hover:text-blue-400 transition-colors">{law.title}</h4>
                    <p className="text-blue-500 text-sm font-black mb-4 uppercase tracking-widest">{law.section}</p>
                    <p className="text-slate-400 text-sm leading-relaxed font-medium">{law.description}</p>
                  </div>
                </div>
                <div className="pt-8 mt-8 border-t border-white/5 flex items-center justify-between">
                  <button className="text-[10px] font-black text-slate-600 uppercase tracking-widest flex items-center gap-2 hover:text-white transition-all">
                    Judicial Archive <ExternalLink size={14}/>
                  </button>
                  <button className="text-blue-500 opacity-0 group-hover:opacity-100 transition-all translate-x-4 group-hover:translate-x-0">
                    <ArrowRight size={20} />
                  </button>
                </div>
              </div>
            ))
          ) : (
            <div className="col-span-full py-24 text-center space-y-6 bg-white/5 rounded-[60px] border-2 border-dashed border-white/5">
              <div className="bg-white/5 w-24 h-24 rounded-full flex items-center justify-center mx-auto text-slate-800">
                <Search size={40} />
              </div>
              <p className="text-slate-500 font-bold text-xl">Statute discovery returned no results.</p>
              <button onClick={() => {setLawSearchQuery(''); setFilterLevel('All'); setSelectedCategory('All');}} className="text-blue-500 text-xs font-black uppercase tracking-widest hover:text-blue-400 underline underline-offset-8">Reset Intelligence Filters</button>
            </div>
          )}
        </div>
      </div>

      {/* Courtroom Admissibility Checklist */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-1 bg-white p-12 rounded-[50px] border border-slate-100 shadow-xl space-y-8">
          <div className="space-y-2">
            <h4 className="text-2xl font-black text-slate-900">Courtroom Prep</h4>
            <p className="text-slate-500 text-sm">Admissibility checklist for Indian Evidence Law compliance.</p>
          </div>
          <div className="space-y-4">
            {[
              "Digital Evidence Hash Verified",
              "Section 65B Certificate Ready",
              "Chain of Custody Intact",
              "AI Rationale Documented",
              "Metadata Integrity Scan"
            ].map((item, i) => (
              <div key={i} className="flex items-center gap-4 p-4 bg-slate-50 rounded-2xl">
                <CheckCircle size={20} className="text-emerald-500" />
                <span className="text-xs font-bold text-slate-700">{item}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="lg:col-span-2 bg-slate-100 p-12 rounded-[50px] border border-slate-200 flex flex-col md:flex-row gap-12 items-center">
          <div className="space-y-6 text-center md:text-left">
            <div className="bg-slate-900 w-16 h-16 rounded-3xl flex items-center justify-center text-white mx-auto md:mx-0">
               <FileWarning size={28}/>
            </div>
            <div className="space-y-2">
              <h4 className="text-2xl font-black text-slate-900">Forensic Expert Bridge</h4>
              <p className="text-sm text-slate-600 max-w-sm">Connect with certified digital forensic witnesses to validate VeriTrust findings for deposition in Indian Courts.</p>
            </div>
            <button className="px-8 py-4 bg-slate-900 text-white rounded-2xl font-black text-xs uppercase tracking-widest hover:bg-slate-800 transition-all">
              Request Forensic Witness
            </button>
          </div>
          <div className="flex-1 grid grid-cols-2 gap-4">
             <div className="bg-white p-6 rounded-3xl shadow-sm text-center border border-slate-200">
               <p className="text-2xl font-black text-slate-900">24h</p>
               <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Avg. Response</p>
             </div>
             <div className="bg-white p-6 rounded-3xl shadow-sm text-center border border-slate-200">
               <p className="text-2xl font-black text-slate-900">50+</p>
               <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Experts in India</p>
             </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TruthLens;
